networks:
  servarrnetwork:
    name: servarrnetwork
    ipam:
      config:
        - subnet: 172.69.0.0/24

services:

  # Radarr
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr
    restart: unless-stopped
    ports:
      - "7878:7878"
    volumes:
      - ./radarr:/config
      - /mnt/nfs/unas/servarr:/data
    environment:
      - PUID=1111
      - PGID=321
      - UMASK=002
      - TZ=America/New_York

  # Sonarr
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr
    restart: unless-stopped
    ports:
      - "8989:8989"
    volumes:
      - ./sonarr:/config
      - /mnt/nfs/unas/servarr:/data
    environment:
      - PUID=2222
      - PGID=321
      - UMASK=002
      - TZ=America/New_York

  # Lidarr
  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr
    restart: unless-stopped
    ports:
      - "8686:8686"
    volumes:
      - ./lidarr:/config
      - /mnt/nfs/unas/servarr:/data
    environment:
      - PUID=3333
      - PGID=321
      - UMASK=002
      - TZ=America/New_York

  # Readarr
  readarr:
    container_name: readarr
    image: ghcr.io/hotio/readarr
    restart: unless-stopped
    ports:
      - "8787:8787"
    volumes:
      - ./readarr:/config
      - /mnt/nfs/unas/servarr:/data
    environment:
      - PUID=4444
      - PGID=321
      - UMASK=002
      - TZ=America/New_York

  # Whisparr

  # Prowlarr
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    restart: unless-stopped
    ports:
      - "9696:9696"
    volumes:
      - ./prowlarr:/config
    environment:
      - PUID=6666
      - PGID=321
      - UMASK=002
      - TZ=America/New_York

  # SABnzbd
  sabnzbd:
    container_name: sabnzbd
    image: ghcr.io/hotio/sabnzbd
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./sabnzbd:/config
      - /mnt/nfs/unas/servarr/usenet:/data/usenet
    environment:
      - PUID=7777
      - PGID=321
      - UMASK=002
      - TZ=America/New_York
      - WEBUI_PORTS=8080/tcp,8080/udp
      - ARGS
